version: '3.8'

services:
  letyca-db:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - letyca-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: letyca
      POSTGRES_USER: letyca
      POSTGRES_DB: letycadb
    # ports:
    #   - 5432:5432

  northwind-db:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ../.devcontainer/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: northwind
    # ports:
    #   - 5433:5432

volumes:
  letyca-db-data:
