version: '3.8'

services:
  autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  traefik:
    restart: unless-stopped
    image: traefik:v2.10
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik-dashboard.priority=100'
      - 'traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)'
      - 'traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080'

  frontend:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./apps/client/docker-pack/Dockerfile
    # ports:
    #   - 14200:80
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`${DOMAIN_NAME}`)'
      - 'traefik.http.services.frontend.loadbalancer.server.port=80'

  backend:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./apps/server/docker-pack/Dockerfile
    # ports:
    #   - 13000:3000
    volumes:
      - ./backend/.env:/app/.env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=PathPrefix(`/api`) && Host(`${DOMAIN_NAME}`)'
      - 'traefik.http.routers.backend.priority=90'
      - 'traefik.http.services.backend.loadbalancer.server.port=3000'

  letyca-db:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - letyca-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: letyca
      POSTGRES_USER: letyca
      POSTGRES_DB: letycadb
    # ports:
    #   - 5432:5432

  northwind-db:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ../.devcontainer/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: northwind
    # ports:
    #   - 5433:5432

volumes:
  letyca-db-data:
